version: '3'
services:
  core:
    build:
      context: .
      args:
        - PORT=3000
    restart: always
    command: bash -c "yarn db:migrate && yarn start"
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - server:/usr/src/app/monkey_production
    environment:
      NODE_ENV: production

volumes:
  server:
