version: '3'
services:
  postgres:
    image: postgres:11.6
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: '${DB_USER}_${NODE_ENV}'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
